name: heroku-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi=0.80
  - pytest=7.1.2
  - pandas=1.4.3
  - flake8=4.0.1
  - scikit-learn=1.1.2
  - requests=2.28.1
  - uvicorn=0.18.2
