name: heroku-app
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.2.2
  - python=3.10
  - fastapi=0.80
  - pytest=7.1.2
  - pandas=1.4.3
  - flake8=4.0.1
  - scikit-learn=1.1.2
  - requests=2.28.1
  - uvicorn=0.18.2
  - jupyter=1.0.0
  - pip:
      - dvc==2.21.0
      - dvc-gdrive==2.19.0
      - mock==4.0.3
      - mock_open==1.4.0
      - black==22.6.0
